objects/Customer_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Additional_comments_or_feedback_for_us__c</fullName>
        <label>Additional comments or feedback for us</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>Customer_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_to_day_functionality_of_the_product__c</fullName>
        <label>Day to day functionality of the product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>1.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>2.Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>2.Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>4.Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>5.Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>5.Extremely dissatisfied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ease_of_use__c</fullName>
        <label>Ease of use</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>1.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>2.Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>2.Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>4.Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>5.Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>5.Extremely dissatisfied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Experience_with_billing_and_accounting__c</fullName>
        <label>Experience with billing and accounting</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>1.Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>1.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>2.Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>2.Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>4.Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>5.Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>5.Extremely dissatisfied</label>
                </value>
                <value>
                    <fullName>6.N/A</fullName>
                    <isActive>false</isActive>
                    <label>6.N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Friendliness_of_the_Customer_Care_team__c</fullName>
        <label>Friendliness of the Customer Care team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>1.Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>1.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>2.Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>2.Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>4.Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>5.Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>5.Extremely dissatisfied</label>
                </value>
                <value>
                    <fullName>6.N/A</fullName>
                    <isActive>false</isActive>
                    <label>6.N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Helpfulness_of_the_Customer_Care_team__c</fullName>
        <label>Helpfulness of the Customer Care team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>1.Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>1.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>2.Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>2.Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>4.Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>5.Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>5.Extremely dissatisfied</label>
                </value>
                <value>
                    <fullName>6.N/A</fullName>
                    <isActive>false</isActive>
                    <label>6.N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_likely_are_you_to_recommend_A3_Smart__c</fullName>
        <label>How likely are you to recommend A3 Smart</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_satisfied_are_you_with_A3_Smart_Home__c</fullName>
        <label>How satisfied are you with A3 Smart Home</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>5.Extremely satisfied</fullName>
                    <default>true</default>
                    <label>5.Extremely satisfied</label>
                </value>
                <value>
                    <fullName>4.Somewhat satisfied</fullName>
                </value>
                <value>
                    <fullName>3.Neither satisfied nor dissatisfied</fullName>
                </value>
                <value>
                    <fullName>2.Somewhat dissatisfied</fullName>
                </value>
                <value>
                    <fullName>1.Extremely dissatisfied</fullName>
                </value>
                <value>
                    <fullName>(1) Extremely satisfied</fullName>
                    <isActive>false</isActive>
                    <label>(1) Extremely satisfied</label>
                </value>
                <value>
                    <fullName>(2)Somewhat satisfied</fullName>
                    <isActive>false</isActive>
                    <label>(2)Somewhat satisfied</label>
                </value>
                <value>
                    <fullName>(3)Neither satisfied nor dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>(3)Neither satisfied nor dissatisfied</label>
                </value>
                <value>
                    <fullName>(4)Somewhat dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>(4)Somewhat dissatisfied</label>
                </value>
                <value>
                    <fullName>(5)Extremely dissatisfied</fullName>
                    <isActive>false</isActive>
                    <label>(5)Extremely dissatisfied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reasons_for_your_score__c</fullName>
        <label>Reasons for your score</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Customer Survey</label>
    <nameField>
        <label>Customer Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyPageExtension.cls
/**************************************************************************************************************************
* 
* Description : Custom Extension for the Customer Survey VF page.
*                Create Customer Survey record associated to case.
* 
* Test class  : TestSurveyPageExtension
* -----------------------------------------------------------------------------------------------------------------------
* 
* ***********************************************************************************************************************/

public class SurveyPageExtension {
    
    public Case case_Obj {get;set;}
    public Customer_Survey__c customer_survey_Obj {get;set;}
    public String surveyId;
    public String OwnerSubString {get;set;}
    public String OwnerLastName;
    
    public SurveyPageExtension(ApexPages.StandardController acon) { 
        OwnerSubString = '';
        OwnerLastName = '';
        String recordID = System.currentPageReference().getParameters().get('id');
        System.debug('******** Record Id '+recordID);
        
        if( recordID != null && recordID != ''){
            System.debug('recordID'+recordID);
            case_Obj = new case();
            case_Obj = [Select id, AR_Customer_Userdef__c, Company__c, owner.name,owner.FirstName from Case where id =: recordID Limit 1][0];
            if(case_Obj!=null){
                system.debug('**** Case obj '+case_Obj);
                system.debug('**** Case obj '+case_Obj.owner.name);
                OwnerLastName = case_Obj.owner.name.Substring(case_Obj.owner.name.indexOf(' ')+1,case_Obj.owner.name.length());
            	OwnerSubString = case_Obj.owner.name.Substring(0,case_Obj.owner.name.indexOf(' ')) + ' ' + OwnerLastName.Substring(0,1);
            }
            else{
                system.debug('**** Case obj NULL');
                OwnerLastName = 'Smart';
            	OwnerSubString = 'Home';
            }
            System.debug('*****OwnerSubString***'+OwnerSubString);
            
            customer_survey_Obj = new Customer_Survey__c();
            customer_survey_Obj.name = 'Test';
            customer_survey_Obj.Case__c = case_Obj.id;
            
            list<Customer_Survey__c> surveylist = new list<Customer_Survey__c>();
            
            surveylist =  [Select id, Additional_comments_or_feedback_for_us__c, Day_to_day_functionality_of_the_product__c,
                           Ease_of_use__c, Experience_with_billing_and_accounting__c, Friendliness_of_the_Customer_Care_team__c,
                           Helpfulness_of_the_Customer_Care_team__c, How_likely_are_you_to_recommend_A3_Smart__c,
                           How_satisfied_are_you_with_A3_Smart_Home__c, Reasons_for_your_score__c,Responsiveness_of_the_Customer_Care_team__c,
                           Satisfaction_with_Customer_Care_team__c from Customer_Survey__c where Case__c =: case_Obj.id Limit 1];
            System.debug('*****test***');
            if( surveylist != null && !surveylist.isEmpty()){
                customer_survey_Obj = surveylist[0];
                surveyId = surveylist[0].Id;    
            }
            
        } 
        
    }
    
    
    public PageReference updateCaseData(){
        if( surveyId != null ){
            customer_survey_Obj.id = surveyId;
            upsert customer_survey_Obj ;
        }
        else{
             surveyId = customer_survey_Obj.id ;
            insert customer_survey_Obj;
        }
        PageReference pageRef;
        if(case_Obj.AR_Customer_Userdef__c == 'AAA')
            pageRef = new PageReference('https://smarthome.calstate.aaa.com/');
        else if(case_Obj.AR_Customer_Userdef__c == 'A3')
            pageRef = new PageReference('https://a3smarthome.com/');
        else
            pageRef = new PageReference('https://gmail.com/');
        
        return pageRef;
    }
    
    
}