objects/Error_Log__c.object
<CustomObject>
    <description>This will log all the error messages if there are any exception thrown from Flow or Apex.</description>
    <fields>
        <fullName>Additional_Info__c</fullName>
        <description>This will have the additional info when exception thrown</description>
        <label>Additional Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Message__c</fullName>
        <description>This will store the Custom Message when exception thrown</description>
        <label>Custom Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>This message will hold the error message thrown from Exception</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Stack_Trace__c</fullName>
        <description>This will have stack trace point for the exception thrown.</description>
        <label>Error Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>This is the source from where exception thrown. Example if it is Apex class then classname-methodname</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QuotePrimaryContact.cls
/* JIRA Num:
* Class Name:QuotePrimaryContact
* Reffered Comp Name: Quote_Preview_And_Send
*/
public class QuotePrimaryContact {
    /* JIRA Num:
* Method Name:getContactEmail
* @param:recordId
* @return:primary contact email
* Description: geting the value from quot related primary contact email
* Modification History: 
*/
    @AuraEnabled
    public static string getContactEmail (Id recordId){
        List<SBQQ__Quote__c> lstQuote = [SELECT Id, SBQQ__PrimaryContact__c,SBQQ__Status__c,SBQQ__PrimaryContact__r.Email
                                         FROM SBQQ__Quote__c 
                                         WHERE id =:recordId LIMIT 1];
        
        if( lstQuote != null && !( lstQuote[0].SBQQ__Status__c == 'Draft' || 
                                  lstQuote[0].SBQQ__Status__c == 'Presented'|| 
                                  lstQuote[0].SBQQ__Status__c == 'Client Rejected')){
                                      return 'Warning :'+'Quote status should be Draft or Presented. Sending email is not availble for status : '+ lstQuote[0].SBQQ__Status__c;
                                  }else if(lstQuote != null && lstQuote[0].SBQQ__PrimaryContact__r.Email != null)
                                  {
                                      return lstQuote[0].SBQQ__PrimaryContact__r.Email;
                                  }
        return null;
        
    }
    /* JIRA Num:
* Method Name:updateContactEmail
* @param:recordId,sent email
* @return:sucess/Error
* Description: updating the sent email value on quote object.
* Modification History: 
*/
    @AuraEnabled
    public static string updateContactEmail (Id recordId,Boolean isSendEmail){
        try{
            List<SBQQ__Quote__c> lstQuote = [SELECT Id, Sent_Email__c,SBQQ__PrimaryContact__c
                                             FROM SBQQ__Quote__c
                                             WHERE id =:recordId
                                             LIMIT 1];
            
            if(lstQuote != null)
            {  
                lstQuote[0].Sent_Email__c = isSendEmail;
                update lstQuote; 
            }
        }catch(Exception ex)
        {
            insert new Error_Log__c(Source__c = 'QuotePrimaryContact-updateContactEmail',
                                    Error_Message__c = ex.getMessage(),
                                    Error_Stack_Trace__c = ex.getStackTraceString(),
                                    Custom_Message__c = 'Exception thrown while updating sent email',
                                    Additional_Info__c = 'quoteId and Sent Email');
            throw new AuraHandledException(ex.getMessage());
        }
        return 'Sucess';
    }
}