objects/Error_Log__c.object
<CustomObject>
    <description>This will log all the error messages if there are any exception thrown from Flow or Apex.</description>
    <fields>
        <fullName>Additional_Info__c</fullName>
        <description>This will have the additional info when exception thrown</description>
        <label>Additional Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Message__c</fullName>
        <description>This will store the Custom Message when exception thrown</description>
        <label>Custom Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>This message will hold the error message thrown from Exception</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Stack_Trace__c</fullName>
        <description>This will have stack trace point for the exception thrown.</description>
        <label>Error Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>This is the source from where exception thrown. Example if it is Apex class then classname-methodname</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Service_Appointment_Snapshot__c.object
<CustomObject>
    <description>This object is used to track the history of service appointments as part of A3SHCRSF3-2</description>
    <fields>
        <fullName>Is_Scheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It will be true if SA is Scheduled as part of A3SHCRSF3-2</description>
        <label>Is Scheduled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Schedule_Start_Time__c</fullName>
        <description>SA Schedule start time as part of A3SHCRSF3-2</description>
        <label>Schedule Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_By__c</fullName>
        <description>SA Scheduled by Agent or Self as part of A3SHCRSF3-2</description>
        <label>Scheduled By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Self-Schedule(Guest)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Appointment__c</fullName>
        <description>Parent SA as part of A3SHCRSF3-2</description>
        <label>Service Appointment</label>
        <referenceTo>ServiceAppointment</referenceTo>
        <relationshipLabel>Service Appointment Snapshots</relationshipLabel>
        <relationshipName>Service_Appointment_Snapshots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Appointment Snapshot</label>
    <nameField>
        <displayFormat>SAS- {0000000}</displayFormat>
        <label>Service Appointment Snapshot #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Appointment Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Service_Appointment_To_SA_Snapshot_Map__mdt.object
<CustomObject>
    <description>STORY NUMBER: A3SHCRSF3-199

The Main Purpose of this is to Map the following Fields from the ServiceAppointment(SA) object to the ServiceAppointmentSnapshot object.

Fields:
AssignedPro, Dispatcher, Status, Self Scheduled, EarliestStartTime(StartDateTime of SA), and DueDate(EndDatetime(SA))</description>
    <fields>
        <fullName>SA_Field_API_Name__c</fullName>
        <description>It Stores the field API name of the ServiceAppointment Object Fields.</description>
        <label>SA Field API Name</label>
        <length>222</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SA_Snapshot_Field_API_Name__c</fullName>
        <description>It Stores the Field Api Name of ServiceAppointment SnapShotObject.</description>
        <label>SA Snapshot Field API Name</label>
        <length>222</length>
        <type>Text</type>
    </fields>
    <label>Service Appointment To SA Snapshot Map</label>
    <pluralLabel>Service Appointment To SA Snapshot Map</pluralLabel>
</CustomObject>

classes/ServiceAppointment_Trigger_Util.cls
public class ServiceAppointment_Trigger_Util {
    
    public static String className = 'ServiceAppointment_Trigger_Util';
    public static String methodName;
    public static Map<Id,Service_Appointment_Snapshot__c> createdSAIdSnapshots = new Map<Id,Service_Appointment_Snapshot__c>();
    public static Map<String,String> saToSnapFieldMapngs {get {
        if(saToSnapFieldMapngs == null){
            Map<String,String> fieldMap = new Map<String,String>();        
            //A3SHCRSF3-199: Retrieving Field Mapping from ServiceAppointment To SA Snapshot metadata
            for(Service_Appointment_To_SA_Snapshot_Map__mdt tempMap : [SELECT SA_Field_API_Name__c,SA_Snapshot_Field_API_Name__c
                                                                       FROM Service_Appointment_To_SA_Snapshot_Map__mdt]){
                fieldMap.put(tempMap.SA_Field_API_Name__c,tempMap.SA_Snapshot_Field_API_Name__c);
            }
            saToSnapFieldMapngs = fieldMap;
        }
        return saToSnapFieldMapngs;
    } set;}
     
    /* A3SHCRSF3-2
     * Method Name:  createSASnapshots
     * Params: newSAs : New Service Appointments
     *         oldSAMap: Old Service Appointments
     * Description: Create SA Snapshots for SA field changes (Status, SchedStartTime, SchedEndTime, Self Scheduled)
     */
    public static void createSASnapshots(List<ServiceAppointment> newSAs, Map<Id,ServiceAppointment> oldSAMap){
        methodName = 'createSASnapshots';
        try{
            List<ServiceAppointment> updatedSAs = new List<ServiceAppointment>();
            List<Service_Appointment_Snapshot__c> newSASnapshots = new List<Service_Appointment_Snapshot__c>();
            
            //Consider All SA's created or updated and skip if the user is not guest user and Original Schedule Time changed
            for(ServiceAppointment tempSA :newSAs){
                if(oldSAMap == null                                                               //Creation
                  || (oldSAMap != null && oldSAMap.containskey(tempSA.Id)                         //Updation                                       
                     && (!(UserInfo.getName() != 'guest Site Guest User' && oldSAMap.get(tempSA.Id).Original_Schedule_Start__c != tempSA.Original_Schedule_Start__c))
                     )){
                    
                    Boolean isSAInsertUpdated = oldSAMap == null ? true: false;
                    //A3SHCRSF3-199:Checking if its update any fields from Metadata mapping got updated or not
                    if(oldSAMap != null && oldSAMap.containskey(tempSA.Id) && saToSnapFieldMapngs.size() > 0){
                        for(String tempSAField :saToSnapFieldMapngs.keySet()){
                            if(oldSAMap.get(tempSA.Id).get(tempSAField) != tempSA.get(tempSAField)){
                            	isSAInsertUpdated = true;
                                break;
                            }    
                        }
                    }
                    
                    if(isSAInsertUpdated){
                    	updatedSAs.add(tempSA);         
                    }                    
                } 
            }
            
            if(updatedSAs.size() > 0){
                for(ServiceAppointment tempSA :updatedSAs){
                    //Create New SA for the changed SA's                    
                    Service_Appointment_Snapshot__c tempSnapShot = createdSAIdSnapshots.containsKey(tempSA.Id) ? createdSAIdSnapshots.get(tempSA.Id)
                        : new Service_Appointment_Snapshot__c(Service_Appointment__c = tempSA.Id);
                    if(Test.isRunningTest()){
                        tempSnapShot = new Service_Appointment_Snapshot__c(Service_Appointment__c = tempSA.Id);
                    }
                    
                    if(saToSnapFieldMapngs.size() > 0){
                        //A3SHCRSF3-199:Iterating over field Map and updating Snapshot record fields with respective SA record field
                        for(String tempSAField :saToSnapFieldMapngs.keySet()){
                            if(String.isNotBlank(saToSnapFieldMapngs.get(tempSAField))){
                                if(saToSnapFieldMapngs.get(tempSAField) == 'Schedule_Start_Time__c'){
                                    DateTime scheduledStartDate = tempSA.Original_Schedule_Start__c != null ? tempSA.Original_Schedule_Start__c : tempSA.SchedStartTime;
                                    tempSnapShot.put(saToSnapFieldMapngs.get(tempSAField),scheduledStartDate);
                                }
                                else{
                                	tempSnapShot.put(saToSnapFieldMapngs.get(tempSAField),tempSA.get(tempSAField));    
                                }                                
                            }  
                        }
                    }
                    
                    //ScheduleStartTime Changed
                    if(oldSAMap != null && oldSAMap.containskey(tempSA.Id) 
                       && oldSAMap.get(tempSA.Id).SchedStartTime != tempSA.SchedStartTime){
                        tempSnapShot.Is_Scheduled__c = true;
                        //Update Scheduled By based on Logged In User
                        tempSnapShot.Scheduled_By__c = UserInfo.getName() == 'guest Site Guest User' ? 'Self-Schedule(Guest)' : 'Agent';                    
                    }
                    
                    newSASnapshots.add(tempSnapShot);
                }
                
                if(newSASnapshots.size() > 0){
                    //Upserting Snapshots
                    upsert newSASnapshots;
                    
                    for(Service_Appointment_Snapshot__c tempSnap :newSASnapshots){
                        createdSAIdSnapshots.put(tempSnap.Service_Appointment__c,tempSnap);
                    }
                }
            }
        }
        catch(Exception e){
            insert new Error_Log__c(Error_Message__c = e.getMessage(),Error_Stack_Trace__c = e.getStackTraceString(),Additional_Info__c = JSON.serialize(newSAs),
                                    Custom_Message__c = 'Error Creating Snapshot records for SA',Source__c = className + '-' + methodName);
        }
    }
}