objects/Error_Log__c.object
<CustomObject>
    <description>This will log all the error messages if there are any exception thrown from Flow or Apex.</description>
    <fields>
        <fullName>Additional_Info__c</fullName>
        <description>This will have the additional info when exception thrown</description>
        <label>Additional Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Message__c</fullName>
        <description>This will store the Custom Message when exception thrown</description>
        <label>Custom Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>This message will hold the error message thrown from Exception</description>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Stack_Trace__c</fullName>
        <description>This will have stack trace point for the exception thrown.</description>
        <label>Error Stack Trace</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>This is the source from where exception thrown. Example if it is Apex class then classname-methodname</description>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateWObasedOnDealerResponse.cls
/*

* Created By : CR Team
* Cerated Date : 5th march 2022
* Description :This class is developed As per the JIRA sotry A3SHCRSF3-77, A3SHCRSF3-83(Sprint 3 Dealer Email functionality).
Based on cusotmer email response updaing  work order record throguht inbound email service.
* Modified History:
* 
* *******/



global class UpdateWObasedOnDealerResponse implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email2, 
                                                           Messaging.InboundEnvelope env)
    {
        string  className='UpdateWObasedOnDealerResponse';
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
   String myPlainText= '';
         myPlainText = email2.plainTextBody;
        String findwo = myPlainText.substringBetween('#$','#$');
               string  woid = findwo.replaceAll( '\\s+', '');                               
        try {
            WorkOrder  wo= [SELECT id,Assigned_Dealer__c,caseID,WorkOrderNumber,Status,  Dealer_Acknowledged__c  
                            FROM WorkOrder  
                            WHERE WorkOrderNumber =:woid  LIMIT 1];
            System.debug('*****wo***'+wo);
            Contact vCon = [SELECT Id, Name, Email 
                            FROM Contact 
                            WHERE Email = :email2.fromAddress 
                            AND AccountId=:wo.Assigned_Dealer__c   LIMIT 1];
            
            List<String> AcceptTerms= System.Label.AcceptTerms.split(',');
            List<String> RejectTerms= System.Label.RejectTerms.split(',');
            
            /*        if(AcceptTerms!= null || RejectTerms!= null){

if(AcceptTerms.contains(myPlainText.toUppercase())){

System.debug('******if yes***');
wo.Dealer_Acknowledged__c  = true;
} else if(RejectTerms.contains(myPlainText.toUppercase())){

System.debug('******if yes***');
wo.Status='Dealer Rejected';   
}
}

*/
            
            if(myPlainText.containsany('Accept')||myPlainText.contains('Yes') ||
               myPlainText.containsany('interested') ||myPlainText.containsany('yeah') || myPlainText.containsany('yep') ) {
                   
                   System.debug('******if yes***');
                   wo.Dealer_Acknowledged__c  = true;
                   
                   
               }  else if(myPlainText.contains('Reject')||myPlainText.contains('NO') ||myPlainText.containsany('not interested')) {
                   System.debug('******If no***');
                   wo.Status='Dealer Rejected';   
               }
            
            update wo;
            System.debug('*****wo after update***'+wo);
            // Create a new Task object 
            Task[] newTask = new Task[0];
            
            // Add a new Task to the contact record we just found above.
            newTask.add(new Task(Description =  myPlainText,
                                 Priority = 'Normal',
                                 Status = 'Inbound Email',
                                 Subject = email2.subject,
                                 IsReminderSet = true,
                                 whatID=wo.CaseID,
                                 ReminderDateTime = System.now()+1,
                                 WhoId =  vCon.Id));
            
         
            insert newTask;    
         
            
        }
        catch (QueryException e) {
            System.debug('Query Issue: ' + e);
            insert new Error_Log__c(Error_Message__c = e.getMessage(),  Error_Stack_Trace__c = e.getStackTraceString(),
                                    Additional_Info__c = 'Inbound email service funtionality', Custom_Message__c = 'Error in updating WO and cretaion of new task',Source__c = className );
          }
        result.success = true;
        return result;
    }
}