objects/Product_tax__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Rate__c</fullName>
        <label>Tax Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Product tax</label>
    <nameField>
        <displayFormat>PRTX-{0000}</displayFormat>
        <label>Product tax Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zip_Code__c.object
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductConsumedTriggerHandlerTest.cls
@isTest
public class ProductConsumedTriggerHandlerTest {
    
    @isTest
    Public static void updateServiceTicketCheck_method1(){
        
        Contact conObj = new Contact(FirstName = 'test', LastName = 'Test',phone='1234567890');
        Database.insert(conObj);
        Id prBook = Test.getStandardPricebookId();
        WorkOrder woObj = new WorkOrder(AccountId = conObj.AccountId,contactId = conObj.Id, 
                                        Status = 'New',Service_Type__c = 'Service Appointment',
                                        City = 'Cha', PostalCode = '21112',Pricebook2Id = prBook );
        Database.insert(woObj);
        
        Product_tax__c prTx = new Product_tax__c (Tax_Rate__c = 10, Zip_Code__c = '21112');
        insert prTx;
        
        priceBook2 pbt = new PriceBook2(name= 'testPrBook');
        insert pbt;
        Product2 prd = new Product2(Name = 'product1');
        insert prd;
        
        PriceBookEntry custPrPrice = new PriceBookEntry (PriceBook2Id = prBook, product2Id = prd.Id,unitPrice = 10,IsActive = true);
        insert custPrPrice;
        Test.startTest();
        ProductConsumed prCons = new ProductConsumed (unitPrice = 10, PricebookEntryId = custPrPrice.Id,
                                                     WorkOrderId = woObj.Id, QuantityConsumed = 1 );
        insert prCons;
        Test.stopTest();
              
        
    }

}